ARG BASE_IMAGE=camera-frigate:current
FROM ${BASE_IMAGE}

COPY --from=trackerfiles tracker-run /etc/s6-overlay/s6-rc.d/frigate/run
RUN sed -i 's/\r$//' /etc/s6-overlay/s6-rc.d/frigate/run \
    && chmod 0755 /etc/s6-overlay/s6-rc.d/frigate/run

HEALTHCHECK NONE
