server {
    listen 5173 ssl;
    server_name _;

    ssl_certificate /run/frontend-tls/fullchain.pem;
    ssl_certificate_key /run/frontend-tls/privkey.pem;

    location /api/ {
        proxy_pass http://frigate:5000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /live/ {
        proxy_pass https://frigate:8971/live/;
        proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }

    location /vod/ {
        proxy_pass https://frigate:8971/vod/;
        proxy_ssl_verify off;
        proxy_set_header Host $http_host;
    }

    location /clips/ {
        proxy_pass https://frigate:8971/clips/;
        proxy_ssl_verify off;
        proxy_set_header Host $http_host;
    }

    location /exports/ {
        proxy_pass https://frigate:8971/exports/;
        proxy_ssl_verify off;
        proxy_set_header Host $http_host;
    }

    location /recordings/ {
        proxy_pass https://frigate:8971/recordings/;
        proxy_ssl_verify off;
        proxy_set_header Host $http_host;
    }

    location /stream/ {
        proxy_pass https://frigate:8971/stream/;
        proxy_ssl_verify off;
        proxy_set_header Host $http_host;
    }

    location /cache/ {
        proxy_pass https://frigate:8971/cache/;
        proxy_ssl_verify off;
        proxy_set_header Host $http_host;
    }

    location /ws/ {
        proxy_pass https://frigate:8971/ws/;
        proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
