#!/command/with-contenv sh
set -eu

cd /opt/frigate

exec python3 -u -m extension.tracker.app \
  --config /config/config.yml \
  --node-id "${TRACKER_NODE_ID:?TRACKER_NODE_ID is required}" \
  --bind 0.0.0.0:50052 \
  --spool-dir /var/lib/camera-tracker/spool \
  --media-dir /media/frigate
